language: ruby
rvm:
 - 2.5.0
before_install:
  - gem install bundler
  - mysql -e 'CREATE DATABASE myapp_test;'
services:
  - mysql
test:
  adapter: mysql2
  database: myapp_test
  username: travis
  encoding: utf8
