language: ruby
rvm:
 - 2.5.0
services:
  - mysql
before_install:
  - gem install bundler
  - mysql -e 'CREATE DATABASE myapp_test;'
test:
  adapter: mysql2
  database: myapp_test
  username: travis2
  encoding: utf8
